version: "3"
services:
  ldap:
    image: edtasixm06/ldap23:latest
    container_name: ldap.edt.org
    hostname: ldap.edt.org
    ports: 
      - "389:389"
    networks:
      - mynet
  dav23:
    image: edtasixm06/dav23:git
    container_name: dav.edt.org
    hostname: dav.edt.org
    privileged: true
    ports:
      - "80:80"
    volumes:
      - "data-dav:/var/www/webdav"
    networks:
      - mynet 
  pam:
    image: edtasixm06/pam23:latest
    container_name: pam.edt.org
    hostname: pem.edt.org
    privileged: true
    networks:
      - mynet
networks:
  mynet:
volumes:
  data-nfs:

